services:
  angular-v18-devcontainer:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ..:/app:cached
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    environment: # Added environment variables
      - NODE_ENV=development  # Set NODE_ENV for proper behavior during dev
